[functions]
directory = "functions/"
[build]
command = """
mkdir -p functions && mkdir -p public &&
cargo install cargo-zigbuild &&
cd crates/hello && cargo zigbuild --target x86_64-unknown-linux-gnu.2.26  --release &&
cd - && cp crates/hello/target/release/hello functions/
"""

[environment]
NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = true
