[functions]
directory = "functions/"
[build]
command = """
mkdir -p functions &&
cd crates/hello && cargo build --release &&
cd - && cp target/release/hello functions/
"""

[environment]
NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = true
