[functions]
directory = "functions/"
[build]
command = """
mkdir -p functions &&
cd crates/hello && AWS_LAMBDA_FUNCTION_NAME=hello cargo build --release &&
cd - && crates/hello/target/release/hello functions/
"""

[environment]
NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = true
